In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv('student-por.csv')
df = pd.DataFrame(data)

print(df["Mjob"].unique())


['at_home' 'health' 'other' 'services' 'teacher']
<class 'numpy.ndarray'>


In [ ]:
uniqueValues = (df['school'].append(df['age']).append(df['famsize'])).unique()
print(uniqueValues)

['GP' 'MS' 18 17 15 16 19 22 20 21 'GT3' 'LE3']


In [ ]:
df.isnull()

school    sex    age  address  famsize  Pstatus   Medu   Fedu   Mjob  \
0     False  False  False    False    False    False  False  False  False   
1     False  False  False    False    False    False  False  False  False   
2     False  False  False    False    False    False  False  False  False   
3     False  False  False    False    False    False  False  False  False   
4     False  False  False    False    False    False  False  False  False   
..      ...    ...    ...      ...      ...      ...    ...    ...    ...   
644   False  False  False    False    False    False  False  False  False   
645   False  False  False    False    False    False  False  False  False   
646   False  False  False    False    False    False  False  False  False   
647   False  False  False    False    False    False  False  False  False   
648   False  False  False    False    False    False  False  False  False   

      Fjob  ...  famrel  freetime  goout   Dalc   Walc  health  absences  \
0    False  ...   False     False  False  False  False   False     False   
1    False  ...   False     False  False  False  False   False     False   
2    False  ...   False     False  False  False  False   False     False   
3    False  ...   False     False  False  False  False   False     False   
4    False  ...   False     False  False  False  False   False     False   
..     ...  ...     ...       ...    ...    ...    ...     ...       ...   
644  False  ...   False     False  False  False  False   False     False   
645  False  ...   False     False  False  False  False   False     False   
646  False  ...   False     False  False  False  False   False     False   
647  False  ...   False     False  False  False  False   False     False   
648  False  ...   False     False  False  False  False   False     False   

        G1     G2     G3  
0    False  False  False  
1    False  False  False  
2    False  False  False  
3    False  False  False  
4    False  False  False  
..     ...    ...    ...  
644  False  False  False  
645  False  False  False  
646  False  False  False  
647  False  False  False  
648  False  False  False  

[649 rows x 33 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64 
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64 
 7   Fedu        649 non-null    int64 
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64 
 13  studytime   649 non-null    int64 
 14  failures    649 non-null    int64 
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher    

In [ ]:
#hence no null value in dataset

In [ ]:
df.fillna(0)

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
644     MS   F   19       R     GT3       T     2     3  services     other   
645     MS   F   18       U     LE3       T     3     1   teacher  services   
646     MS   F   18       U     GT3       T     1     1     other     other   
647     MS   M   17       U     LE3       T     3     1  services  services   
648     MS   M   18       R     LE3       T     3     2  services     other   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        4   0  11  11  
1    ...      5        3      3     1     1      3        2   9  11  11  
2    ...      4        3      2     2     3      3        6  12  13  12  
3    ...      3        2      2     1     1      5        0  14  14  14  
4    ...      4        3      2     1     2      5        0  11  13  13  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
644  ...      5        4      2     1     2      5        4  10  11  10  
645  ...      4        3      4     1     1      1        4  15  15  16  
646  ...      1        1      1     1     1      5        6  11  12   9  
647  ...      2        4      5     3     4      2        6  10  10  10  
648  ...      4        4      1     3     4      5        4  10  11  11  

[649 rows x 33 columns]

In [ ]:
df.fillna(method='pad')

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
644     MS   F   19       R     GT3       T     2     3  services     other   
645     MS   F   18       U     LE3       T     3     1   teacher  services   
646     MS   F   18       U     GT3       T     1     1     other     other   
647     MS   M   17       U     LE3       T     3     1  services  services   
648     MS   M   18       R     LE3       T     3     2  services     other   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        4   0  11  11  
1    ...      5        3      3     1     1      3        2   9  11  11  
2    ...      4        3      2     2     3      3        6  12  13  12  
3    ...      3        2      2     1     1      5        0  14  14  14  
4    ...      4        3      2     1     2      5        0  11  13  13  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
644  ...      5        4      2     1     2      5        4  10  11  10  
645  ...      4        3      4     1     1      1        4  15  15  16  
646  ...      1        1      1     1     1      5        6  11  12   9  
647  ...      2        4      5     3     4      2        6  10  10  10  
648  ...      4        4      1     3     4      5        4  10  11  11  

[649 rows x 33 columns]

In [ ]:
df.fillna(method='bfill')

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
644     MS   F   19       R     GT3       T     2     3  services     other   
645     MS   F   18       U     LE3       T     3     1   teacher  services   
646     MS   F   18       U     GT3       T     1     1     other     other   
647     MS   M   17       U     LE3       T     3     1  services  services   
648     MS   M   18       R     LE3       T     3     2  services     other   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        4   0  11  11  
1    ...      5        3      3     1     1      3        2   9  11  11  
2    ...      4        3      2     2     3      3        6  12  13  12  
3    ...      3        2      2     1     1      5        0  14  14  14  
4    ...      4        3      2     1     2      5        0  11  13  13  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
644  ...      5        4      2     1     2      5        4  10  11  10  
645  ...      4        3      4     1     1      1        4  15  15  16  
646  ...      1        1      1     1     1      5        6  11  12   9  
647  ...      2        4      5     3     4      2        6  10  10  10  
648  ...      4        4      1     3     4      5        4  10  11  11  

[649 rows x 33 columns]

In [ ]:
df2 = df[['age', 'G1', 'G2', 'G3']].copy()
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     649 non-null    int64
 1   G1      649 non-null    int64
 2   G2      649 non-null    int64
 3   G3      649 non-null    int64
dtypes: int64(4)
memory usage: 20.4 KB


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled = scaler.fit_transform(df2)
print(scaled)

[[0.42857143 0.         0.57894737 0.57894737]
 [0.28571429 0.47368421 0.57894737 0.57894737]
 [0.         0.63157895 0.68421053 0.63157895]
 ...
 [0.42857143 0.57894737 0.63157895 0.47368421]
 [0.28571429 0.52631579 0.52631579 0.52631579]
 [0.42857143 0.52631579 0.57894737 0.57894737]]


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# transform data
scaled = scaler.fit_transform(df2)
print(scaled)

[[ 1.03169516 -4.15547029 -0.19581961 -0.28065755]
 [ 0.21013668 -0.87456978 -0.19581961 -0.28065755]
 [-1.43298028  0.21906372  0.49113675  0.02911583]
 ...
 [ 1.03169516 -0.14548078  0.14765857 -0.90020431]
 [ 0.21013668 -0.51002528 -0.53929779 -0.59043093]
 [ 1.03169516 -0.51002528 -0.19581961 -0.28065755]]


In [ ]:
df3 = df[['age','studytime','freetime','goout','G1', 'G2', 'G3','higher']].copy()
df3.head()

age  studytime  freetime  goout  G1  G2  G3 higher
0   18          2         3      4   0  11  11    yes
1   17          2         3      3   9  11  11    yes
2   15          2         3      2  12  13  12    yes
3   15          3         2      2  14  14  14    yes
4   16          2         3      2  11  13  13    yes

In [ ]:
df3.higher=df3.higher.map(dict(yes=1, no=0))

In [ ]:
df3.tail()

age  studytime  freetime  goout  G1  G2  G3  higher
644   19          3         4      2  10  11  10       1
645   18          2         3      4  15  15  16       1
646   18          2         1      1  11  12   9       1
647   17          1         4      5  10  10  10       1
648   18          1         4      1  10  11  11       1

In [ ]:
print(df3["higher"].unique())

[1 0]


In [ ]:
X = df3.iloc[:, :-1].values
y = df3.iloc[:, 7].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

[[  5  10]
 [  3 177]]
              precision    recall  f1-score   support

           0       0.62      0.33      0.43        15
           1       0.95      0.98      0.96       180

    accuracy                           0.93       195
   macro avg       0.79      0.66      0.70       195
weighted avg       0.92      0.93      0.92       195



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=4,metric='manhattan')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  8   7]
 [  8 172]]
              precision    recall  f1-score   support

           0       0.50      0.53      0.52        15
           1       0.96      0.96      0.96       180

    accuracy                           0.92       195
   macro avg       0.73      0.74      0.74       195
weighted avg       0.93      0.92      0.92       195



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3,metric='minkowski')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[  7   8]
 [  7 173]]
              precision    recall  f1-score   support

           0       0.50      0.47      0.48        15
           1       0.96      0.96      0.96       180

    accuracy                           0.92       195
   macro avg       0.73      0.71      0.72       195
weighted avg       0.92      0.92      0.92       195



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=2,metric='euclidean')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 11   4]
 [ 26 154]]
              precision    recall  f1-score   support

           0       0.30      0.73      0.42        15
           1       0.97      0.86      0.91       180

    accuracy                           0.85       195
   macro avg       0.64      0.79      0.67       195
weighted avg       0.92      0.85      0.87       195

